name: sqlbuilder-zero-ci

on:
  push:
    branches:
      - main

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v2
        with:
          go-version: '1.22.3'

      - name: Install Jzero and Grum
        run: |
          go install github.com/jaronnie/grum@latest

      - name: Test Usage and upload
        run: |
          GITHUB_TOKEN=${{ secrets.ACCESS_TOKEN }} grum clone https://github.com/jzero-io/jzero
          cp -r .template/go-zero/model ./jzero/.template/go-zero
          cd jzero
          git add .
          git diff-index --quiet HEAD || git commit -m "chore(template): update .template go-zero/model"
          git push -f
